framework:
    secret: "%env(APP_SECRET)%"
    translator:
        fallbacks: ["en"]
    default_locale: "%env(APP_LOCALE)%"
    csrf_protection: null
    # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
    session:
        handler_id: ~
    #esi: ~
    #fragments: ~
    php_errors:
        log: true
    router:
        strict_requirements: null
