security:
    encoders:
    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false



    access_control:

        - { path: ^/, role: ROLE_USER }
