security:
    encoders:
        'ParkManager\Core\Infrastructure\Security\AdministratorSecurityUser':
            algorithm: argon2i

    providers:
        administrator:
            id: 'park_manager.security.user_provider.administrator'

    firewalls:
        dev:
            pattern: '^/(_(profiler|wdt)|css|images|js)/'
            security: false

        admin:
            request_matcher: park_manager.section.admin.request_matcher
            provider: administrator
            context: admin
            anonymous: ~

            logout:
                csrf_parameter:       _csrf_token
                csrf_token_generator: security.csrf.token_manager
                csrf_token_id:        logout_admin
                path:                 '%park_manager.section.admin.prefix%logout'
                target:               '%park_manager.section.admin.prefix%'
            guard:
                authenticators:
                    - park_manager.security.guard.form.administrator

            remember_me:
                secret:               "%env(APP_SECRET)%"
                token_provider:       ~
                catch_exceptions:     true
                name:                 ADMIN_REMEMBERME
                lifetime:             604800 # one week
                path:                 '%park_manager.section.admin.prefix%'
                domain:               '%park_manager.section.admin.domain%'
                secure:               '%park_manager.section.admin.is_secure%'
                httponly:             true
                always_remember_me:   false

        client:
            request_matcher: park_manager.section.admin.request_matcher
            provider: administrator
            anonymous: ~

            logout:
                csrf_parameter:       _csrf_token
                csrf_token_generator: security.csrf.token_manager
                csrf_token_id:        logout_admin
                path:                 '%park_manager.section.client.prefix%logout'
                target:               '%park_manager.section.client.prefix%'
            guard:
                authenticators:
                    - park_manager.security.guard.form.administrator

            remember_me:
                secret:               "%env(APP_SECRET)%"
                token_provider:       ~
                catch_exceptions:     true
                name:                 ADMIN_REMEMBERME
                lifetime:             604800 # one week
                path:                 '%park_manager.section.client.prefix%'
                domain:               '%park_manager.section.client.domain%'
                secure:               '%park_manager.section.client.is_secure%'
                httponly:             true
                always_remember_me:   false

    access_control:
        # Notice. Path always ends with a /

        # Admin
        -
            path: '%park_manager.section.admin.path%login$'
            host: '%park_manager.section.admin.host_pattern%'
            requires_channel: '%park_manager.section.admin.channel%'

            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: '%park_manager.section.admin.path%resetting'
            host: '%park_manager.section.admin.host_pattern%'
            requires_channel: '%park_manager.section.admin.channel%'

            role: IS_AUTHENTICATED_ANONYMOUSLY

        -
            path: '%park_manager.section.admin.path%'
            host: '%park_manager.section.admin.host_pattern%'
            requires_channel: '%park_manager.section.admin.channel%'

            role: ROLE_ADMIN

        # Client
        -
            path: '%park_manager.section.client.path%'
            host: '%park_manager.section.client.host_pattern%'
            requires_channel: '%park_manager.section.client.channel%'

            role: ROLE_USER
