#sylius_mailer:
#    sender:
#        name: No-reply
#        address: no-reply@example.com
#    emails:
#        park_manager.user.reset_password:
#            subject: Reset Password
#            template: '@ParkManagerUser/mail/password_reset.twig'
#
#        park_manager.user.confirm_email_address_change:
#            subject: Confirm your e-mail address
#            template: '@ParkManagerUser/mail/confirm_email_address_change.twig'
