# Gush configuration file, any comments will be lost.
meta-header: |
    Copyright (c) the Contributors as noted in the AUTHORS file.

    This file is part of the Park-Manager project.

    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.

pr_type:
    - minor
    - bug
    - feature
    - refactor
    - style
    - security
table-pr:
    bug_fix: ['Bug Fix?', 'no']
    new_feature: ['New Feature?', 'no']
    bc_breaks: ['BC Breaks?', 'no']
    deprecations: ['Deprecations?', 'no']
    related_issues: ['Fixed Tickets', '']
    license: ['License', 'MPL-2.0']
repo_adapter: github
issue_tracker: github
repo_org: park-manager
repo_name: park-manager
issue_project_org: park-manager
issue_project_name: park-manager
