language: php

sudo: false

branches:
    only:
        - master

matrix:
    include:
        - php: '7.1'
        - php: '7.1'
          env: deps='low'
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
    - if [[ ! $deps ]]; then composer update --prefer-source --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'dev' ]]; then composer config minimum-stability dev && composer update --prefer-source --no-progress --no-suggest --ansi ; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-source --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
    - make tests
