language: php

sudo: false

branches:
    only:
        - master

matrix:
    include:
        - php: '7.1'
          env: lint=1
    fast_finish: true

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"
    - echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - if [[ $lint = 1 ]]; then wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.3.1/php-cs-fixer.phar; fi
    - if [[ $lint = 1 ]]; then composer global require phpstan/phpstan; fi
    - export PATH="$PATH:$HOME/.composer/vendor/bin:./vendor/bin"

install:
    - if [[ ! $deps ]]; then composer update --prefer-source --no-progress --no-suggest --ansi; fi
    - if [[ $deps = 'dev' ]]; then composer config minimum-stability dev && composer update --prefer-source --no-progress --no-suggest --ansi ; fi
    - if [[ $deps = 'low' ]]; then composer update --prefer-source --no-progress --no-suggest --prefer-stable --prefer-lowest --ansi; fi

script:
    - make tests
    - if [[ $lint = 1 ]]; then php php-cs-fixer.phar fix --dry-run --diff --no-ansi; fi
    - if [[ $lint = 1 ]]; then phpstan analyse -c phpstan.neon -l5 --ansi src web bin; fi
