park_manager.administrator.security_login:
    path: /login
    defaults: { _controller: park_manager.web_action.security.administrator.login }
    methods: 'GET|POST'

park_manager.administrator.security_logout:
    path: /logout
    defaults: { _controller: 'ParkManager\Bundle\UserBundle\Action\SecurityLogoutAction' }
    methods: GET

park_manager.administrator.request_password_reset:
    path: /resetting
    defaults: { _controller: park_manager.web_action.security.administrator.request_password_reset }
    methods: 'GET|POST'

park_manager.administrator.confirm_password_reset:
    path: /resetting/confirm/{token}
    defaults: { _controller: park_manager.web_action.security.administrator.confirm_password_reset }
    methods: 'GET|POST'
    requirements:
        token: '.+' # Token can contain slashes
