# The routing system of Park-Manager uses the Rollerworks RouteAutowiringBundle
# To register routing information into slot. See https://github.com/rollerworks/RouteAutowiringBundle

# On top of that the Rollerworks AppSectioningBundle provides the section specific loading
# of routing information from a autowired routing-slot.
#
# Avoid registering routes here directly but instead use the RouteAutowiringBundle
# and/or Symfony Flex to ensure bundle removal doesn't break the application.

_admin:
    resource: 'admin:rollerworks_autowiring#park_manager.admin_section.root'
    type: app_section

_client:
    resource: 'client:rollerworks_autowiring#park_manager.client_section.root'
    type: app_section

home:
    path: /
    controller: ParkManager\Core\Infrastructure\Web\Action\HomepageAction

admin_home:
    path: /admin/
    controller: ParkManager\Core\Infrastructure\Web\Action\HomepageAction

#admin_login:
#    path: /admin/login
#    defaults: { _controller: 'park_manager.web_action.security.login.administrator' }
