# The routing system of Park-Manager uses the Rollerworks RouteAutowiringBundle
# To register routing information into slot. See https://github.com/rollerworks/RouteAutowiringBundle

# On top of that the Rollerworks AppSectioningBundle provides the section specific loading
# of routing information from a autowired routing-slot.
#
# Avoid registering routes here directly but instead use the RouteAutowiringBundle
# and/or Symfony Flex to ensure bundle removal doesn't break the application.

# XXX Use a custom route loader `park_manager.sections_loader; automatically loads admin,api,client (in order)
# with the correct configuration (prefix, host (admin and API (catch all) only), schemas (https))
#
# Move to config/routes/park_manager.yaml

_park_manager:
    type: park_manager_sections_loader
    resource: .
